apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  Namespace: poc-namespace
spec:
  selector:
    app: user-management-app
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer